-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users Table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  phone_number VARCHAR(15) UNIQUE NOT NULL,
  full_name VARCHAR(255),
  email VARCHAR(255),
  -- Unique shareable referral code. Auto-generated by trigger on INSERT.
  referral_code VARCHAR(20) UNIQUE,
  -- FK to the user who referred this person. Set at signup and never changed.
  referred_by UUID REFERENCES users(id) ON DELETE SET NULL,
  claimed_free_sample BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON COLUMN users.referral_code IS 'Unique shareable referral code. Auto-generated by trigger on INSERT.';
COMMENT ON COLUMN users.referred_by   IS 'FK to the user who referred this person. Set at signup time and never changed.';

-- Addresses Table
CREATE TABLE addresses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) DEFAULT 'Home',
  address_line1 VARCHAR(255) NOT NULL,
  address_line2 VARCHAR(255),
  landmark VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(10),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  is_default BOOLEAN DEFAULT false,
  delivery_instructions TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Products Table
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  volume VARCHAR(50),
  price DECIMAL(10, 2) NOT NULL,
  deposit_amount DECIMAL(10, 2) DEFAULT 0.00,
  image_url TEXT,
  -- Array of {label, value} objects for nutritional data per 100ml serving
  nutritional_info JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Marketing bullet points for the product
  features TEXT[] NOT NULL DEFAULT '{}',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT chk_nutritional_info_is_array CHECK (jsonb_typeof(nutritional_info) = 'array')
);

-- Discounts Table (promo / coupon code definitions)
-- Defined before subscriptions/orders so that orders can reference discounts(id).
CREATE TABLE discounts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Always stored UPPER CASE; unique index enforces case-insensitive uniqueness
  code VARCHAR(50) UNIQUE NOT NULL,

  description TEXT,

  -- 'percentage' | 'flat_amount'
  discount_type VARCHAR(20) NOT NULL,
  CONSTRAINT valid_discount_type CHECK (discount_type IN ('percentage', 'flat_amount')),

  -- For 'percentage': 0-100. For 'flat_amount': rupee value.
  discount_value DECIMAL(10, 2) NOT NULL,
  CONSTRAINT positive_discount_value CHECK (discount_value > 0),

  -- Caps rupee savings for percentage codes (e.g. max ₹100 off)
  max_discount_amount DECIMAL(10, 2),
  CONSTRAINT positive_max_discount CHECK (max_discount_amount IS NULL OR max_discount_amount > 0),

  -- Minimum cart/order amount required to apply this code
  min_order_amount DECIMAL(10, 2) DEFAULT 0.00,

  -- Scope: 'all' | 'subscription' | 'one_time' | 'wallet_recharge'
  applicable_to VARCHAR(20) DEFAULT 'all',
  CONSTRAINT valid_applicable_to CHECK (applicable_to IN ('all', 'subscription', 'one_time', 'wallet_recharge')),

  -- Optional: restrict to a single product
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,

  -- NULL = unlimited global uses
  max_uses INTEGER,
  CONSTRAINT positive_max_uses CHECK (max_uses IS NULL OR max_uses > 0),

  -- Denormalized counter maintained by trigger
  current_uses INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT non_negative_uses CHECK (current_uses >= 0),

  -- How many times a single user can redeem this code
  max_uses_per_user INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT positive_max_uses_per_user CHECK (max_uses_per_user > 0),

  is_first_order_only BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true,

  -- NULL = discount applies without an order count limit (e.g. one-time / wallet recharge).
  -- Set to e.g. 7 to give 7 discounted deliveries on a subscription then revert to full price.
  max_discount_orders INTEGER,
  CONSTRAINT positive_max_discount_orders CHECK (max_discount_orders IS NULL OR max_discount_orders > 0),

  valid_from  TIMESTAMP WITH TIME ZONE,
  valid_until TIMESTAMP WITH TIME ZONE,
  CONSTRAINT valid_validity_range CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from),

  -- Flexible JSON for future extensions (campaign tags, A/B test group, etc.)
  metadata JSONB,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE discounts IS 'Promo/discount code definitions administered through the backend.';
COMMENT ON COLUMN discounts.code IS 'Always stored and queried in UPPER CASE.';
COMMENT ON COLUMN discounts.current_uses IS 'Denormalized counter kept in sync by trigger on discount_usages.';

-- Subscriptions Table
CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id),
  address_id UUID REFERENCES addresses(id) ON DELETE SET NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  frequency VARCHAR(50) DEFAULT 'daily',
  status VARCHAR(50) DEFAULT 'active',
  quantity INTEGER DEFAULT 1,
  delivery_time VARCHAR(50) DEFAULT 'morning',
  interval_days INTEGER,
  custom_quantities JSONB,
  paused_dates TEXT[] DEFAULT '{}',
  discount_code_id UUID REFERENCES discounts(id) ON DELETE SET NULL,
  discount_amount DECIMAL(10, 2) DEFAULT 0.00,
  -- Countdown set to discounts.max_discount_orders at checkout.
  -- The order-generation backend job decrements this on each discounted delivery.
  -- When it reaches 0 (or is NULL with no limit), orders revert to full price.
  discount_orders_remaining INTEGER,
  CONSTRAINT non_negative_discount_orders CHECK (discount_orders_remaining IS NULL OR discount_orders_remaining >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_frequency CHECK (frequency IN ('daily', 'custom', 'on_interval', 'buy_once')),
  CONSTRAINT valid_status CHECK (status IN ('active', 'paused', 'cancelled', 'completed'))
);

COMMENT ON COLUMN subscriptions.discount_code_id IS 'Discount code applied at the time of subscription creation.';
COMMENT ON COLUMN subscriptions.discount_amount IS 'Rupee value discounted at checkout for this subscription.';
COMMENT ON COLUMN subscriptions.discount_orders_remaining IS 'Countdown of discounted deliveries remaining. NULL means no order-count limit was set on the code. Decremented by the order generation job.';

-- Add comments for documentation
COMMENT ON COLUMN subscriptions.interval_days IS 'For on_interval frequency mode: number of days between deliveries (2-30)';
COMMENT ON COLUMN subscriptions.custom_quantities IS 'For custom frequency mode: JSON object with per-day quantities, e.g. {"0": 2, "1": 1, "2": 0, ...} where keys are weekday indexes (0=Sunday, 6=Saturday)';

-- Orders Table
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  subscription_id UUID REFERENCES subscriptions(id),
  product_id UUID REFERENCES products(id),
  delivery_date DATE NOT NULL,
  status VARCHAR(50) DEFAULT 'scheduled',
  quantity INTEGER DEFAULT 1,
  amount DECIMAL(10, 2),
  address_id UUID REFERENCES addresses(id) ON DELETE SET NULL,
  delivery_notes TEXT,
  delivered_at TIMESTAMP WITH TIME ZONE,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  cancellation_reason TEXT,
  discount_code_id UUID REFERENCES discounts(id) ON DELETE SET NULL,
  discount_amount DECIMAL(10, 2) DEFAULT 0.00,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_status CHECK (status IN ('scheduled', 'in_transit', 'delivered', 'on_hold', 'cancelled', 'failed'))
);

COMMENT ON COLUMN orders.discount_code_id IS 'FK to the discount code applied at checkout.';
COMMENT ON COLUMN orders.discount_amount IS 'Rupee value discounted on this order.';

-- Bottle Returns Table
CREATE TABLE bottle_returns (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  order_id UUID REFERENCES orders(id),
  return_date DATE,
  quantity INTEGER DEFAULT 1,
  status VARCHAR(50) DEFAULT 'pending',
  collected_at TIMESTAMP WITH TIME ZONE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_status CHECK (status IN ('pending', 'requested', 'collected', 'completed', 'cancelled'))
);

-- Wallets Table
CREATE TABLE wallets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  balance DECIMAL(10, 2) DEFAULT 0.00,
  low_balance_threshold DECIMAL(10, 2) DEFAULT 100.00,
  auto_recharge_enabled BOOLEAN DEFAULT false,
  auto_recharge_amount DECIMAL(10, 2),
  auto_recharge_trigger_amount DECIMAL(10, 2),
  razorpay_customer_id VARCHAR(255),
  razorpay_subscription_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT positive_balance CHECK (balance >= 0)
);

-- Transactions Table
CREATE TABLE transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transaction_id VARCHAR(100) UNIQUE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  wallet_id UUID REFERENCES wallets(id),
  order_id UUID REFERENCES orders(id),
  type VARCHAR(50) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  balance_before DECIMAL(10, 2),
  balance_after DECIMAL(10, 2),
  description TEXT,
  payment_method VARCHAR(50),
  payment_gateway_id VARCHAR(255),
  payment_gateway_response JSONB,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_type CHECK (type IN ('credit', 'debit', 'refund', 'adjustment')),
  CONSTRAINT valid_status CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled'))
);

-- Discount Usages Table (one row per redemption; full audit history)
-- Defined after orders so orders(id) FK resolves.
CREATE TABLE discount_usages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  discount_id UUID NOT NULL REFERENCES discounts(id) ON DELETE RESTRICT,
  user_id     UUID NOT NULL REFERENCES users(id)     ON DELETE CASCADE,

  -- NULL for wallet-recharge redemptions
  order_id UUID REFERENCES orders(id) ON DELETE SET NULL,

  -- Actual rupee value saved (may differ from discount_value after caps/rounding)
  discount_amount_applied DECIMAL(10, 2) NOT NULL,
  CONSTRAINT positive_discount_applied CHECK (discount_amount_applied >= 0),

  original_amount DECIMAL(10, 2) NOT NULL,
  final_amount    DECIMAL(10, 2) NOT NULL,

  -- 'applied' → normal; 'reversed' → order cancelled, usage slot released
  status VARCHAR(20) NOT NULL DEFAULT 'applied',
  CONSTRAINT valid_usage_status CHECK (status IN ('applied', 'reversed')),

  applied_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  reversed_at TIMESTAMP WITH TIME ZONE,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE discount_usages IS 'Immutable audit log of every discount code redemption.';
COMMENT ON COLUMN discount_usages.status IS 'Set to "reversed" on order cancellation to release the usage slot.';

-- Offers/Creatives Table
CREATE TABLE offers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  image_url TEXT,
  link_url TEXT,
  offer_type VARCHAR(50),
  discount_percentage DECIMAL(5, 2),
  discount_amount DECIMAL(10, 2),
  valid_from TIMESTAMP WITH TIME ZONE,
  valid_until TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User Preferences Table
CREATE TABLE user_preferences (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  language VARCHAR(10) DEFAULT 'en',
  notifications_enabled BOOLEAN DEFAULT true,
  sms_notifications BOOLEAN DEFAULT true,
  email_notifications BOOLEAN DEFAULT false,
  push_notifications BOOLEAN DEFAULT true,
  theme VARCHAR(20) DEFAULT 'light',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_language CHECK (language IN ('en', 'hi', 'kn'))
);

-- Referrals Table
-- One row per referral event. referral_code lives on users; this is the event log.
CREATE TABLE referrals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- The user whose code was shared
  referrer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- The new user who signed up using the code
  referee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT unique_referee UNIQUE (referee_id),
  CONSTRAINT no_self_referral CHECK (referrer_id != referee_id),

  -- The first completed order that triggered reward payout. NULL while pending.
  qualifying_order_id UUID REFERENCES orders(id) ON DELETE SET NULL,

  -- Snapshot of reward amounts at creation so future app_settings changes
  -- don't retroactively affect already-pending referrals.
  referrer_reward_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  CONSTRAINT positive_referrer_reward CHECK (referrer_reward_amount >= 0),

  referee_reward_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  CONSTRAINT positive_referee_reward CHECK (referee_reward_amount >= 0),

  -- pending   → signed up, no qualifying order yet
  -- qualified → first order placed, rewards processing
  -- rewarded  → wallet credited for both parties
  -- expired   → no order placed before expires_at
  -- cancelled → manually voided
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  CONSTRAINT valid_status CHECK (status IN ('pending', 'qualified', 'rewarded', 'expired', 'cancelled')),

  -- Separate timestamps — both parties may be credited at different times
  referrer_rewarded_at TIMESTAMP WITH TIME ZONE,
  referee_rewarded_at  TIMESTAMP WITH TIME ZONE,

  -- Deadline for referee to place first order (typically 30 days after signup)
  expires_at TIMESTAMP WITH TIME ZONE,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE referrals IS 'One row per referral signup event. A user can be a referee only once.';
COMMENT ON COLUMN referrals.qualifying_order_id    IS 'First completed order that triggered reward payout.';
COMMENT ON COLUMN referrals.referrer_reward_amount IS 'Wallet credit snapshotted at referral creation for the referrer.';
COMMENT ON COLUMN referrals.referee_reward_amount  IS 'Wallet credit snapshotted at referral creation for the referee.';
COMMENT ON COLUMN referrals.expires_at             IS 'If referee does not order before this date the row moves to expired.';

-- Subscription Holds Table
CREATE TABLE subscription_holds (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  subscription_id UUID REFERENCES subscriptions(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- Delivery Preferences Table
CREATE TABLE delivery_preferences (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  preference_type VARCHAR(100),
  ring_doorbell BOOLEAN DEFAULT true,
  leave_at_door BOOLEAN DEFAULT false,
  hand_delivery BOOLEAN DEFAULT false,
  special_instructions TEXT,
  preferred_delivery_time VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FAQ Table
CREATE TABLE faqs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category VARCHAR(100),
  language VARCHAR(10) DEFAULT 'en',
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Support Tickets Table
CREATE TABLE support_tickets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ticket_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  subject VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(100),
  status VARCHAR(50) DEFAULT 'open',
  priority VARCHAR(50) DEFAULT 'medium',
  assigned_to UUID,
  resolved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_status CHECK (status IN ('open', 'in_progress', 'resolved', 'closed', 'cancelled')),
  CONSTRAINT valid_priority CHECK (priority IN ('low', 'medium', 'high', 'urgent'))
);

-- Notifications Table
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50),
  reference_id UUID,
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- App Settings Table (Global settings)
CREATE TABLE app_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  setting_key VARCHAR(100) UNIQUE NOT NULL,
  setting_value TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES for better query performance
-- ============================================

-- Users indexes
CREATE INDEX        idx_users_phone         ON users(phone_number);
CREATE UNIQUE INDEX idx_users_referral_code ON users(UPPER(referral_code));

-- Referrals indexes
CREATE INDEX idx_referrals_referrer_id ON referrals(referrer_id);
CREATE INDEX idx_referrals_referee_id  ON referrals(referee_id);
CREATE INDEX idx_referrals_expires_at  ON referrals(expires_at) WHERE status = 'pending';

-- Addresses indexes
CREATE INDEX idx_addresses_user_id ON addresses(user_id);
CREATE INDEX idx_addresses_default ON addresses(user_id, is_default);
CREATE UNIQUE INDEX idx_unique_address_name_per_user ON addresses(user_id, LOWER(name));

-- Subscriptions indexes
CREATE INDEX idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);
CREATE INDEX idx_subscriptions_active ON subscriptions(user_id, status) WHERE status = 'active';
CREATE UNIQUE INDEX idx_unique_active_subscription ON subscriptions(user_id, product_id, address_id) WHERE status = 'active';

-- Orders indexes
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_delivery_date ON orders(delivery_date);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_subscription_id ON orders(subscription_id);
CREATE INDEX idx_orders_user_delivery ON orders(user_id, delivery_date DESC);

-- Discounts indexes
CREATE UNIQUE INDEX idx_discounts_code         ON discounts(UPPER(code));
CREATE        INDEX idx_discounts_active_valid ON discounts(is_active, valid_from, valid_until) WHERE is_active = true;
CREATE        INDEX idx_discount_usages_discount_id ON discount_usages(discount_id);
CREATE        INDEX idx_discount_usages_user_id     ON discount_usages(user_id);
CREATE        INDEX idx_discount_usages_order_id    ON discount_usages(order_id);
CREATE UNIQUE INDEX idx_discount_usage_per_order    ON discount_usages(order_id) WHERE order_id IS NOT NULL AND status = 'applied';
CREATE        INDEX idx_discount_usages_user_discount ON discount_usages(discount_id, user_id) WHERE status = 'applied';
CREATE        INDEX idx_orders_discount_code ON orders(discount_code_id) WHERE discount_code_id IS NOT NULL;

-- Transactions indexes
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_wallet_id ON transactions(wallet_id);
CREATE INDEX idx_transactions_created ON transactions(created_at DESC);
CREATE INDEX idx_transactions_type_status ON transactions(type, status);

-- Bottle Returns indexes
CREATE INDEX idx_bottle_returns_user_id ON bottle_returns(user_id);
CREATE INDEX idx_bottle_returns_status ON bottle_returns(status);
CREATE INDEX idx_bottle_returns_order_id ON bottle_returns(order_id);

-- Notifications indexes
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id, is_read) WHERE is_read = false;

-- Wallets indexes
CREATE INDEX idx_wallets_user_id ON wallets(user_id);

-- ============================================
-- TRIGGERS for updated_at
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger: auto-generate referral_code on user INSERT
-- Format: FIRSTNAME (max 6 chars) + 3 random digits (e.g. DONALD123)
-- Falls back to 8-char random if full_name is NULL at INSERT time.
CREATE OR REPLACE FUNCTION generate_referral_code()
RETURNS TRIGGER AS $$
DECLARE
  first_name TEXT;
  base_code  TEXT;
  code       TEXT;
  fallback_chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
BEGIN
  IF NEW.full_name IS NOT NULL AND TRIM(NEW.full_name) != '' THEN
    first_name := UPPER(REGEXP_REPLACE(SPLIT_PART(TRIM(NEW.full_name), ' ', 1), '[^A-Za-z]', '', 'g'));
    base_code  := LEFT(first_name, 6);
  ELSE
    base_code := NULL;
  END IF;

  LOOP
    IF base_code IS NOT NULL AND LENGTH(base_code) > 0 THEN
      code := base_code || LPAD(floor(random() * 1000)::int::text, 3, '0');
    ELSE
      code := '';
      FOR i IN 1..8 LOOP
        code := code || substr(fallback_chars, floor(random() * length(fallback_chars) + 1)::int, 1);
      END LOOP;
    END IF;

    EXIT WHEN NOT EXISTS (SELECT 1 FROM users WHERE referral_code = code);
  END LOOP;

  NEW.referral_code := code;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_referral_code
  BEFORE INSERT ON users
  FOR EACH ROW
  WHEN (NEW.referral_code IS NULL)
  EXECUTE FUNCTION generate_referral_code();

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_addresses_updated_at BEFORE UPDATE ON addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_bottle_returns_updated_at BEFORE UPDATE ON bottle_returns FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_wallets_updated_at BEFORE UPDATE ON wallets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_offers_updated_at BEFORE UPDATE ON offers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_preferences_updated_at BEFORE UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_subscription_holds_updated_at BEFORE UPDATE ON subscription_holds FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_delivery_preferences_updated_at BEFORE UPDATE ON delivery_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON app_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_discounts_updated_at BEFORE UPDATE ON discounts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_discount_usages_updated_at BEFORE UPDATE ON discount_usages FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Trigger: increment current_uses on discount_usages INSERT
CREATE OR REPLACE FUNCTION increment_discount_uses()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE discounts SET current_uses = current_uses + 1 WHERE id = NEW.discount_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_increment_discount_uses
  AFTER INSERT ON discount_usages
  FOR EACH ROW EXECUTE FUNCTION increment_discount_uses();

-- Trigger: decrement current_uses when a usage is reversed
CREATE OR REPLACE FUNCTION decrement_discount_uses()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'reversed' AND OLD.status != 'reversed' THEN
    UPDATE discounts SET current_uses = GREATEST(current_uses - 1, 0) WHERE id = NEW.discount_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_decrement_discount_uses
  AFTER UPDATE ON discount_usages
  FOR EACH ROW EXECUTE FUNCTION decrement_discount_uses();

-- ============================================
-- ROW LEVEL SECURITY (RLS) Policies
-- ============================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE discount_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE bottle_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;

-- Referrals: users can see rows where they are referrer or referee
CREATE POLICY "Users can view own referrals"
  ON referrals FOR SELECT
  USING (
    auth.uid()::text = referrer_id::text OR
    auth.uid()::text = referee_id::text
  );
ALTER TABLE subscription_holds ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

-- Users: Users can only read/update their own data
CREATE POLICY "Users can view own data" ON users FOR SELECT USING (auth.uid()::text = id::text);
CREATE POLICY "Users can update own data" ON users FOR UPDATE USING (auth.uid()::text = id::text);

-- Addresses: Users can manage their own addresses
CREATE POLICY "Users can view own addresses" ON addresses FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own addresses" ON addresses FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own addresses" ON addresses FOR UPDATE USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can delete own addresses" ON addresses FOR DELETE USING (auth.uid()::text = user_id::text);

-- Subscriptions: Users can manage their own subscriptions
CREATE POLICY "Users can view own subscriptions" ON subscriptions FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own subscriptions" ON subscriptions FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own subscriptions" ON subscriptions FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Orders: Users can view their own orders
CREATE POLICY "Users can view own orders" ON orders FOR SELECT USING (auth.uid()::text = user_id::text);

-- Bottle Returns: Users can manage their own returns
CREATE POLICY "Users can view own bottle returns" ON bottle_returns FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own bottle returns" ON bottle_returns FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own bottle returns" ON bottle_returns FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Wallets: Users can view their own wallet
CREATE POLICY "Users can view own wallet" ON wallets FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own wallet" ON wallets FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Transactions: Users can view their own transactions
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT USING (auth.uid()::text = user_id::text);

-- User Preferences: Users can manage their own preferences
CREATE POLICY "Users can view own preferences" ON user_preferences FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own preferences" ON user_preferences FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own preferences" ON user_preferences FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Delivery Preferences: Users can manage their own preferences
CREATE POLICY "Users can view own delivery preferences" ON delivery_preferences FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own delivery preferences" ON delivery_preferences FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own delivery preferences" ON delivery_preferences FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Notifications: Users can view their own notifications
CREATE POLICY "Users can view own notifications" ON notifications FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can update own notifications" ON notifications FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Support Tickets: Users can view and create their own tickets
CREATE POLICY "Users can view own support tickets" ON support_tickets FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own support tickets" ON support_tickets FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

-- Products and Offers: Public read access
CREATE POLICY "Anyone can view active products" ON products FOR SELECT USING (is_active = true);
CREATE POLICY "Anyone can view active offers" ON offers FOR SELECT USING (is_active = true);

-- Discounts: authenticated users can read active codes; writes via service-role only
CREATE POLICY "Anyone can view active discounts" ON discounts FOR SELECT USING (is_active = true);

-- Discount usages: users can only see their own redemptions
CREATE POLICY "Users can view own discount usages" ON discount_usages FOR SELECT USING (auth.uid()::text = user_id::text);

-- FAQs: Public read access
CREATE POLICY "Anyone can view active FAQs" ON faqs FOR SELECT USING (is_active = true);

-- App Settings: Public read access
CREATE POLICY "Anyone can view app settings" ON app_settings FOR SELECT USING (true);

-- ============================================
-- DISCOUNT CODE VALIDATION FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION validate_discount_code(
  p_code          VARCHAR,
  p_user_id       UUID,
  p_order_amount  DECIMAL,
  p_applicable_to VARCHAR DEFAULT 'all'
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_discount     discounts%ROWTYPE;
  v_user_uses    INTEGER;
  v_discount_amt DECIMAL(10, 2);
BEGIN
  SELECT * INTO v_discount
  FROM discounts
  WHERE UPPER(code) = UPPER(p_code)
    AND is_active = true
    AND (valid_from  IS NULL OR valid_from  <= NOW())
    AND (valid_until IS NULL OR valid_until >= NOW());

  IF NOT FOUND THEN
    RETURN json_build_object('valid', false, 'error', 'Invalid or expired discount code.');
  END IF;

  IF v_discount.max_uses IS NOT NULL AND v_discount.current_uses >= v_discount.max_uses THEN
    RETURN json_build_object('valid', false, 'error', 'This discount code has reached its usage limit.');
  END IF;

  SELECT COUNT(*) INTO v_user_uses
  FROM discount_usages
  WHERE discount_id = v_discount.id AND user_id = p_user_id AND status = 'applied';

  IF v_user_uses >= v_discount.max_uses_per_user THEN
    RETURN json_build_object('valid', false, 'error', 'You have already used this discount code.');
  END IF;

  IF p_order_amount < v_discount.min_order_amount THEN
    RETURN json_build_object(
      'valid', false,
      'error', format('A minimum order amount of ₹%s is required to use this code.', v_discount.min_order_amount)
    );
  END IF;

  IF v_discount.applicable_to != 'all' AND v_discount.applicable_to != p_applicable_to THEN
    RETURN json_build_object('valid', false, 'error', 'This discount code is not applicable for this order type.');
  END IF;

  IF v_discount.is_first_order_only THEN
    IF EXISTS (
      SELECT 1 FROM orders
      WHERE user_id = p_user_id AND status NOT IN ('cancelled', 'failed') LIMIT 1
    ) THEN
      RETURN json_build_object('valid', false, 'error', 'This discount code is only valid on your first order.');
    END IF;
  END IF;

  IF v_discount.discount_type = 'percentage' THEN
    v_discount_amt := ROUND(p_order_amount * v_discount.discount_value / 100.0, 2);
    IF v_discount.max_discount_amount IS NOT NULL THEN
      v_discount_amt := LEAST(v_discount_amt, v_discount.max_discount_amount);
    END IF;
  ELSE
    v_discount_amt := LEAST(v_discount.discount_value, p_order_amount);
  END IF;

  RETURN json_build_object(
    'valid',                true,
    'discount_id',          v_discount.id,
    'discount_type',        v_discount.discount_type,
    'discount_value',       v_discount.discount_value,
    'discount_amount',      v_discount_amt,
    'final_amount',         ROUND(p_order_amount - v_discount_amt, 2),
    'max_discount_orders',  v_discount.max_discount_orders
  );
END;
$$;

COMMENT ON FUNCTION validate_discount_code IS
  'Validates a promo code for a given user and order amount. Safe to call from the app layer before inserting a discount_usage row.';

-- ============================================
-- REFERRAL CODE: check_referral_code FUNCTION
-- ============================================
-- Lightweight read-only check used for inline UI validation.
-- Does NOT apply the code — use apply_referral_code for that.

DROP FUNCTION IF EXISTS check_referral_code(TEXT);

CREATE OR REPLACE FUNCTION check_referral_code(p_code TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN json_build_object('valid', false, 'error', 'Not authenticated.');
  END IF;

  IF EXISTS (
    SELECT 1 FROM users WHERE id = v_caller_id AND referred_by IS NOT NULL
  ) THEN
    RETURN json_build_object('valid', false, 'error', 'You have already used a referral code.');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM users
    WHERE UPPER(referral_code) = UPPER(TRIM(p_code))
      AND id != v_caller_id
  ) THEN
    RETURN json_build_object('valid', false, 'error', 'Invalid referral code.');
  END IF;

  RETURN json_build_object('valid', true);
END;
$$;

COMMENT ON FUNCTION check_referral_code IS
  'Read-only check: returns { valid: true } if the code exists, is not the caller''s own code, '
  'and the caller has not already used a referral code. Does NOT apply the code.';

-- ============================================
-- INITIAL DATA SEEDING
-- ============================================

-- Insert default product (500ml milk bottle)
INSERT INTO products (name, description, volume, price, deposit_amount, image_url, is_active)
VALUES 
('Fresh Milk 500ml', 'Farm fresh organic milk delivered daily in glass bottles', '500ml', 30.00, 50.00, 'https://placeholder-url.com/milk-bottle.jpg', true);

-- Insert some app settings
INSERT INTO app_settings (setting_key, setting_value, description)
VALUES 
('order_modification_cutoff_time', '19:00', 'Time after which orders cannot be modified for next day (24-hour format)'),
('min_wallet_balance', '100', 'Minimum wallet balance required'),
('min_wallet_recharge', '350', 'Minimum wallet recharge amount'),
('max_unreturned_bottles', '5', 'Maximum number of unreturned bottles allowed'),
('referral_reward_amount', '50', 'Reward amount for successful referrals'),
('delivery_charge', '0', 'Delivery charge per order');

-- Insert sample FAQs
INSERT INTO faqs (question, answer, category, language, display_order, is_active)
VALUES 
('How do I pause my subscription?', 'You can pause your subscription from the Subscriptions tab. Go to your active subscription and select "Pause Subscription". Choose the dates you want to pause for.', 'Subscription', 'en', 1, true),
('What is the bottle deposit?', 'A refundable deposit of ₹50 is charged for each glass bottle. This will be refunded when you return the bottle.', 'Billing', 'en', 2, true),
('How do I add money to my wallet?', 'Go to the Wallet tab and click on "Recharge". You can add money using UPI, card, or net banking.', 'Wallet', 'en', 3, true),
('Can I change my delivery address?', 'Yes, you can change your delivery address from Account > Manage Addresses. Make sure to update it before 7 PM for next day delivery.', 'Delivery', 'en', 4, true);

-- Add missing INSERT policy for users table
CREATE POLICY "Users can insert own data" ON users FOR INSERT WITH CHECK (auth.uid()::text = id::text);

-- Add missing INSERT policy for wallets table  
CREATE POLICY "Users can insert own wallet" ON wallets FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

-- ============================================
-- REFERRAL CODE: apply_referral_code FUNCTION
-- ============================================
-- Atomic SECURITY DEFINER RPC called from the app when the user
-- submits a referral code during sign-up.  It validates the code,
-- updates users.referred_by, and inserts the referrals row all
-- inside one transaction so there is never a partial state.

DROP FUNCTION IF EXISTS apply_referral_code(TEXT);

CREATE OR REPLACE FUNCTION apply_referral_code(p_code TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id   UUID := auth.uid();
  v_referrer_id UUID;
  v_reward      DECIMAL(10,2);
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Not authenticated.');
  END IF;

  IF EXISTS (
    SELECT 1 FROM users WHERE id = v_caller_id AND referred_by IS NOT NULL
  ) THEN
    RETURN json_build_object('success', false, 'error', 'You have already used a referral code.');
  END IF;

  SELECT id INTO v_referrer_id
  FROM users
  WHERE UPPER(referral_code) = UPPER(TRIM(p_code))
    AND id != v_caller_id;

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Invalid referral code.');
  END IF;

  SELECT COALESCE(setting_value::DECIMAL, 50.00) INTO v_reward
  FROM app_settings
  WHERE setting_key = 'referral_reward_amount'
  LIMIT 1;

  v_reward := COALESCE(v_reward, 50.00);

  UPDATE users
  SET referred_by = v_referrer_id
  WHERE id = v_caller_id;

  INSERT INTO referrals (
    referrer_id,
    referee_id,
    referrer_reward_amount,
    referee_reward_amount,
    expires_at
  ) VALUES (
    v_referrer_id,
    v_caller_id,
    v_reward,
    v_reward,
    NOW() + INTERVAL '30 days'
  );

  RETURN json_build_object(
    'success',       true,
    'referrer_id',   v_referrer_id,
    'reward_amount', v_reward
  );
END;
$$;

COMMENT ON FUNCTION apply_referral_code IS
  'Validates a referral code, sets users.referred_by, and inserts the referrals row atomically. '
  'SECURITY DEFINER bypasses RLS safely after internal auth.uid() checks. '
  'Returns JSON: { success, error? } on failure or { success, referrer_id, reward_amount } on success.';

-- ============================================
-- FREE SAMPLE CONFIG TABLE
-- ============================================

CREATE TABLE free_sample_config (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  is_enabled BOOLEAN NOT NULL DEFAULT false,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity_per_day INTEGER NOT NULL DEFAULT 1,
  trial_days INTEGER NOT NULL DEFAULT 3,
  delivery_time VARCHAR(50) NOT NULL DEFAULT 'morning',
  description TEXT,
  banner_image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT positive_quantity CHECK (quantity_per_day > 0),
  CONSTRAINT positive_trial_days CHECK (trial_days > 0 AND trial_days <= 30)
);

COMMENT ON TABLE free_sample_config IS 'Single-row admin config for the free sample / trial feature.';
COMMENT ON COLUMN users.claimed_free_sample IS 'Set to true once the user has claimed their free sample.';

CREATE TRIGGER update_free_sample_config_updated_at
  BEFORE UPDATE ON free_sample_config
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE free_sample_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view free sample config"
  ON free_sample_config FOR SELECT
  USING (true);

-- Seed default config
INSERT INTO free_sample_config (is_enabled, product_id, quantity_per_day, trial_days, delivery_time, description)
SELECT true, p.id, 1, 3, 'morning', 'Try our farm-fresh milk free for 3 days! 1 bottle (500ml) delivered daily.'
FROM products p WHERE p.name = 'Fresh Milk 500ml' AND p.is_active = true LIMIT 1;

-- ============================================
-- CLAIM FREE SAMPLE FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION claim_free_sample(p_dates DATE[], p_address_id UUID DEFAULT NULL)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id     UUID := auth.uid();
  v_config        free_sample_config%ROWTYPE;
  v_date          DATE;
  v_order_number  TEXT;
  v_orders        JSON[];
  v_address_id    UUID;
  v_random_chars  TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_code          TEXT;
  v_tomorrow      DATE := (CURRENT_DATE + INTERVAL '1 day')::DATE;
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Not authenticated.');
  END IF;

  IF EXISTS (SELECT 1 FROM users WHERE id = v_caller_id AND claimed_free_sample = true) THEN
    RETURN json_build_object('success', false, 'error', 'You have already claimed your free sample.');
  END IF;

  SELECT * INTO v_config FROM free_sample_config WHERE is_enabled = true LIMIT 1;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Free samples are not available at this time.');
  END IF;

  IF p_dates IS NULL OR array_length(p_dates, 1) IS NULL OR array_length(p_dates, 1) = 0 THEN
    RETURN json_build_object('success', false, 'error', 'Please select at least one delivery date.');
  END IF;

  IF array_length(p_dates, 1) > v_config.trial_days THEN
    RETURN json_build_object('success', false, 'error', format('You can select up to %s delivery dates.', v_config.trial_days));
  END IF;

  FOREACH v_date IN ARRAY p_dates LOOP
    IF v_date < v_tomorrow THEN
      RETURN json_build_object('success', false, 'error', format('Delivery date %s must be tomorrow or later.', v_date));
    END IF;
  END LOOP;

  IF (SELECT COUNT(DISTINCT d) FROM unnest(p_dates) d) != array_length(p_dates, 1) THEN
    RETURN json_build_object('success', false, 'error', 'Duplicate delivery dates are not allowed.');
  END IF;

  IF p_address_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM addresses WHERE id = p_address_id AND user_id = v_caller_id) THEN
      RETURN json_build_object('success', false, 'error', 'Invalid delivery address.');
    END IF;
    v_address_id := p_address_id;
  ELSE
    SELECT id INTO v_address_id FROM addresses WHERE user_id = v_caller_id ORDER BY is_default DESC, created_at ASC LIMIT 1;
  END IF;

  IF v_address_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Please add a delivery address before claiming your free sample.');
  END IF;

  v_orders := ARRAY[]::JSON[];

  FOREACH v_date IN ARRAY p_dates LOOP
    LOOP
      v_code := 'FS-';
      FOR i IN 1..8 LOOP
        v_code := v_code || substr(v_random_chars, floor(random() * length(v_random_chars) + 1)::int, 1);
      END LOOP;
      EXIT WHEN NOT EXISTS (SELECT 1 FROM orders WHERE order_number = v_code);
    END LOOP;
    v_order_number := v_code;

    INSERT INTO orders (order_number, user_id, subscription_id, product_id, delivery_date, status, quantity, amount, address_id, delivery_notes)
    VALUES (v_order_number, v_caller_id, NULL, v_config.product_id, v_date, 'scheduled', v_config.quantity_per_day, 0.00, v_address_id, 'Free sample delivery');

    v_orders := v_orders || json_build_object('order_number', v_order_number, 'delivery_date', v_date, 'quantity', v_config.quantity_per_day, 'amount', 0.00)::JSON;
  END LOOP;

  UPDATE users SET claimed_free_sample = true WHERE id = v_caller_id;

  RETURN json_build_object('success', true, 'orders', array_to_json(v_orders), 'message', format('Successfully claimed %s free sample deliveries!', array_length(p_dates, 1)));
END;
$$;

COMMENT ON FUNCTION claim_free_sample IS
  'Atomic free-sample claim. Validates eligibility, creates free orders, and sets users.claimed_free_sample = true.';