-- ============================================
-- REFERRALS REDESIGN MIGRATION
-- Drops the old single-table design and
-- replaces it with a proper two-part model:
--   1. users.referral_code  — a user's own code
--   2. users.referred_by    — who recruited them
--   3. referrals            — one row per referral event
-- ============================================


-- ============================================
-- 1. DROP OLD TABLE
-- ============================================

DROP TABLE IF EXISTS referrals;


-- ============================================
-- 2. ALTER USERS TABLE
-- Add referral_code (the user's shareable code)
-- and referred_by (FK to the referrer's user row).
-- ============================================

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS referral_code VARCHAR(20) UNIQUE,
  ADD COLUMN IF NOT EXISTS referred_by   UUID REFERENCES users(id) ON DELETE SET NULL;

COMMENT ON COLUMN users.referral_code IS 'Unique shareable referral code. Auto-generated by trigger on INSERT.';
COMMENT ON COLUMN users.referred_by   IS 'FK to the user who referred this person. Set at signup time and never changed.';


-- ============================================
-- 3. REFERRAL CODE GENERATOR TRIGGER
-- Format: FIRSTNAME (max 6 chars) + 3 random digits
-- e.g. DONALD123, TRUMP456
-- Falls back to 8-char random if full_name is NULL
-- (full_name is set on complete-profile screen, after user row creation).
-- Loops until the generated code is unique.
-- ============================================

DROP TRIGGER IF EXISTS trg_generate_referral_code ON users;
DROP FUNCTION IF EXISTS generate_referral_code();

CREATE OR REPLACE FUNCTION generate_referral_code()
RETURNS TRIGGER AS $$
DECLARE
  first_name TEXT;
  base_code  TEXT;
  code       TEXT;
  fallback_chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
BEGIN
  -- Extract first name: take text before the first space, strip non-alpha, uppercase, cap at 6 chars
  IF NEW.full_name IS NOT NULL AND TRIM(NEW.full_name) != '' THEN
    first_name := UPPER(REGEXP_REPLACE(SPLIT_PART(TRIM(NEW.full_name), ' ', 1), '[^A-Za-z]', '', 'g'));
    base_code  := LEFT(first_name, 6);
  ELSE
    base_code := NULL;
  END IF;

  LOOP
    IF base_code IS NOT NULL AND LENGTH(base_code) > 0 THEN
      -- Name-seeded: FIRSTNAME + 3 random digits (000-999)
      code := base_code || LPAD(floor(random() * 1000)::int::text, 3, '0');
    ELSE
      -- Fallback: 8 random chars from unambiguous set
      code := '';
      FOR i IN 1..8 LOOP
        code := code || substr(fallback_chars, floor(random() * length(fallback_chars) + 1)::int, 1);
      END LOOP;
    END IF;

    EXIT WHEN NOT EXISTS (SELECT 1 FROM users WHERE referral_code = code);
  END LOOP;

  NEW.referral_code := code;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_referral_code
  BEFORE INSERT ON users
  FOR EACH ROW
  WHEN (NEW.referral_code IS NULL)
  EXECUTE FUNCTION generate_referral_code();


-- ============================================
-- 4. NEW REFERRALS TABLE
-- One row per referral event (one signup per
-- referee — enforced by UNIQUE on referee_id).
-- Tracks status progression and both-sided
-- reward amounts separately for full auditability.
-- ============================================

CREATE TABLE referrals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- The user whose code was shared
  referrer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- The new user who signed up using the code
  referee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- A user can only ever be referred once
  CONSTRAINT unique_referee UNIQUE (referee_id),

  -- Referrer and referee cannot be the same person
  CONSTRAINT no_self_referral CHECK (referrer_id != referee_id),

  -- The first completed order that triggered reward payout. NULL while pending.
  qualifying_order_id UUID REFERENCES orders(id) ON DELETE SET NULL,

  -- Snapshot of rewards at creation time so changes to app_settings don't
  -- retroactively affect already-pending referrals.
  referrer_reward_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  CONSTRAINT positive_referrer_reward CHECK (referrer_reward_amount >= 0),

  referee_reward_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  CONSTRAINT positive_referee_reward CHECK (referee_reward_amount >= 0),

  -- Lifecycle status:
  --   pending   → referee signed up, has not yet placed first qualifying order
  --   qualified → first order placed, rewards are being processed
  --   rewarded  → wallet credited for both referrer and referee
  --   expired   → referee never ordered within the expiry window
  --   cancelled → manually voided by admin
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  CONSTRAINT valid_status CHECK (status IN ('pending', 'qualified', 'rewarded', 'expired', 'cancelled')),

  -- Separate credit timestamps — both parties may be rewarded at different times
  referrer_rewarded_at TIMESTAMP WITH TIME ZONE,
  referee_rewarded_at  TIMESTAMP WITH TIME ZONE,

  -- Deadline for referee to place first order (typically 30 days after signup)
  expires_at TIMESTAMP WITH TIME ZONE,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE referrals IS 'One row per referral signup event. A user can be a referee only once.';
COMMENT ON COLUMN referrals.qualifying_order_id    IS 'First completed order that triggered reward payout.';
COMMENT ON COLUMN referrals.referrer_reward_amount IS 'Wallet credit snapshotted at referral creation for the referrer.';
COMMENT ON COLUMN referrals.referee_reward_amount  IS 'Wallet credit snapshotted at referral creation for the referee.';
COMMENT ON COLUMN referrals.expires_at             IS 'If referee does not order before this date the row moves to expired.';


-- ============================================
-- 5. INDEXES
-- ============================================

-- Fast lookup of all referrals made by a user (for the refer.tsx stats card)
CREATE INDEX idx_referrals_referrer_id ON referrals(referrer_id);

-- Fast lookup of a user's own referral origin
CREATE INDEX idx_referrals_referee_id  ON referrals(referee_id);

-- Pending expiry sweeper job
CREATE INDEX idx_referrals_expires_at  ON referrals(expires_at) WHERE status = 'pending';

-- Case-insensitive referral code lookup at signup
CREATE UNIQUE INDEX idx_users_referral_code ON users(UPPER(referral_code));


-- ============================================
-- 6. ROW LEVEL SECURITY
-- ============================================

ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;

-- Users can see referrals where they are the referrer (to show their stats)
-- or the referee (to see how they were onboarded)
CREATE POLICY "Users can view own referrals"
  ON referrals FOR SELECT
  USING (
    auth.uid()::text = referrer_id::text OR
    auth.uid()::text = referee_id::text
  );

-- Inserts are handled exclusively by the service-role edge function at signup.
-- No direct INSERT policy means clients cannot fake referral rows.


-- ============================================
-- 7. REGENERATE CODE WHEN full_name IS FIRST SET
-- The INSERT trigger runs before full_name is known
-- (phone-only signup). This UPDATE trigger fires
-- the first time full_name changes from NULL to a
-- real value (complete-profile screen) and replaces
-- the random fallback with a name-seeded code.
-- ============================================

DROP TRIGGER IF EXISTS trg_regenerate_referral_code_on_name ON users;
DROP FUNCTION IF EXISTS regenerate_referral_code_on_name();

CREATE OR REPLACE FUNCTION regenerate_referral_code_on_name()
RETURNS TRIGGER AS $$
DECLARE
  first_name TEXT;
  base_code  TEXT;
  code       TEXT;
BEGIN
  IF OLD.full_name IS NULL AND NEW.full_name IS NOT NULL AND TRIM(NEW.full_name) != '' THEN
    first_name := UPPER(REGEXP_REPLACE(SPLIT_PART(TRIM(NEW.full_name), ' ', 1), '[^A-Za-z]', '', 'g'));
    base_code  := LEFT(first_name, 6);

    IF base_code IS NOT NULL AND LENGTH(base_code) > 0 THEN
      LOOP
        code := base_code || LPAD(floor(random() * 1000)::int::text, 3, '0');
        EXIT WHEN NOT EXISTS (SELECT 1 FROM users WHERE referral_code = code AND id != NEW.id);
      END LOOP;
      NEW.referral_code := code;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_regenerate_referral_code_on_name
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION regenerate_referral_code_on_name();
